name: Release
on:
  push:
    branches: [dai/develop]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: "17"
      - name: Publish ${{ github.ref }}
        run: sbt ci-release
        env:
          NEXUS_HOST: "nexus.xebialabs.com"
          NEXUS_USERNAME: ${{ secrets.NEXUS_CI_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_CI_USER_PWD }}
